
name: V2LY Not Master

on:
  push:
    branches:
      - '!master'

jobs:
  lang:    
    name: Lang
    runs-on: self-hosted
    steps:
    - name: Check out
      uses: actions/checkout@v2      
    - name: Use Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Lang
      run: |
        npm ci
        cp lang/en.json lang/en.orig.json
        npm run build:lang
        diff lang/en.json lang/en.orig.json
      
  lint:
    name: Lint
    runs-on: self-hosted
    steps:
    - name: Check out
      uses: actions/checkout@v2      
    - name: Use Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Lint
      run: |
        npm ci
        npx standard
          
  component:
    name: Component Tests
    runs-on: self-hosted
    steps:
    - name: Check out
      uses: actions/checkout@v2      
    - name: Use Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        mongoms_download_mirror: http://downloads.mongodb.org
        mongoms_version: 4.0.5
        mongoms_disable_postinstall: 1
        ci_node_index: 0
        ci_node_total: 1
    - name: Component Tests          
      run: |
        npm ci
        npm test        